config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :people, controllers: {registrations: "registrations"}
  resources :people do
    resources :wall_posts
  end
  resources :friendships
  resources :groups do
    member do
      post 'people', :to => "groups#add_person", :as => :add_person_to
      delete 'people', :to => "groups#remove_person", :as => :remove_person_from
    end
  end

  resources :wall_posts

  root 'welcome#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :friendships, -> {where(accepted: true)}, :foreign_key => "requester_id"
  has_many :friends, :through => :friendships

  has_many :awaiting_friendships, -> {where(accepted: false)}, :foreign_key => "requester_id", :class_name => "Friendship"
  has_many :awaiting_friends, :through => :awaiting_friendships

  has_many :pending_friendships, -> {where(accepted: false)}, :foreign_key => "granter_id", :class_name => "Friendship"
  has_many :pending_friends, :through => :pending_friendships

  has_many :wall_posts
  has_and_belongs_to_many :groups

  mount_uploader :photo, PhotoUploader

  def self.search(name)
    if name
      where("name LIKE :name", {:name => "%#{name}%"})
    else
      find(:all)
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_person!

  # GET /people
  # GET /people.json
  #
  # if a search parameter is supplied, the people will be limited
  # to those with a name like the search parameter
  def index
    if params[:search]
      @people = Person.search(params[:search])
    else
      @people = Person.all
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :interests, :hobbies, :status, :relationship, :photo)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="row">
<div class="col-lg-6">



<%= form_for(@person, :html => {:multipart => true}) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="field form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :interests %><br>
    <%= f.text_field :interests, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :hobbies %><br>
    <%= f.text_field :hobbies, class: "form-control" %>
  </div>
    <div class="field form-group">
      <%= f.label :status %><br>
      <%= f.text_field :status, class: "form-control" %>
    </div>
  <div class="field form-group">
    <%= f.label :relationship %><br>
    <%= f.text_field :relationship, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>

app/views/people/edit.html.erb
<h1>Editing My Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>All People</h1>
<%= form_tag(people_path, :method => :get) do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search People" %>
    <%= submit_tag "Search" %>
<%end %>
<table class="table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Manage Friend</th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
  <% if current_person != person %>
      <tr>
        <td><%= link_to person.name, person %></td>
        <td><%= person.email %></td>
        <% if current_person.friends.include? person %>
            <td><%= button_to "Remove Friend",
                              friendship_path(:id => current_person.friendships.find_by(:requester_id => current_person.id, :granter_id => person.id).id),
                              :method => :delete, class: "btn btn-danger"%></td>
        <% elsif current_person.pending_friends.include? person %>
            <td>
              <%= button_to "Accept Friend Request",
                            friendship_path(:id => current_person.pending_friendships.find_by(:requester_id => person.id, :granter_id => current_person.id).id,
                                            :accepted => true), :method => :put, class: "btn btn-success" %>
            </td>
        <% elsif current_person.awaiting_friends.include? person %>
            <td><%= button_to "Cancel Friend Request",
                              friendship_path(:id => current_person.awaiting_friendships.find_by(:requester_id => current_person.id, :granter_id => person.id).id),
                              :method => :delete, class: "btn btn-warning" %></td>
        <%else %>
            <td><%= button_to "Add Friend", friendships_path(:granter_id => person, :accepted => false), :method => :post, class: "btn btn-default" %></td>
        <% end %>
      </tr>
    <% end %>
      <%end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class="clearfix">
  <div class="pull-right">
    <%= image_tag @person.photo_url, height:"200" %>
  </div>
  <div>
    <h1><%= @person.name %><br /><small><%= @person.status %></small></h1>
    <% if @person == current_person %>
      <%= link_to 'Edit My Profile', edit_person_path(@person), class: "btn btn-default" %>
    <% end %>
  </div>
</div>

<hr />
<div class="row">
  <div class="row">
    <div class="col-lg-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          Contact Me
        </div>
        <div class="panel-body">
          <p>
            <span class="label label-info">Name:</span>
            <%= @person.name %>
          </p>

          <p>
            <span class="label label-info">Email:</span>
            <%= @person.email %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          About Me
        </div>
        <div class="panel-body">
          <p>
            <span class="label label-info">Interests:</span>
            <%= @person.interests %>
          </p>
          <p>
            <span class="label label-info">Hobbies:</span>
            <%= @person.hobbies %>
          </p>
          <p>
            <span class="label label-info">Status:</span>
            <%= @person.status %>
          </p>
          <p>
            <span class="label label-info">Relationship:</span>
            <%= @person.relationship %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          My Friends
        </div>
        <div class="panel-body">
          <% @person.friends.each do |friend| %>
              <%= link_to friend do %>
                <%= image_tag friend.photo_url, size: "64", alt: friend.name %>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          My Groups
        </div>
        <div class="panel-body">
          <ul>
            <% @person.groups.each do |group| %>
                <li><%= link_to group.name, group %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          My Wall
        </div>
        <div class="panel-body">
          <table class="table-striped">
            <% @person.wall_posts.each do |wall_post| %>
                <tr>
                  <td>
                    <%= render partial: "wall_posts/show", locals:{wall_post: wall_post} %>
                  </td>
                </tr>
            <% end %>
          </table>
          <%= link_to "New Post", new_person_wall_post_path(:person_id => @person.id) %>
        </div>
      </div>
    </div>
  </div>
</div>