config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :people, controllers: {registrations: "registrations"}
  resources :people do
    resources :wall_posts
  end
  resources :friendships
  resources :groups do
    member do
      post 'people', :to => "groups#add_person", :as => :add_person_to
      delete 'people', :to => "groups#remove_person", :as => :remove_person_from
    end
  end

  resources :wall_posts

  root 'welcome#index'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

  belongs_to :person, :foreign_key => "requester_id"
  belongs_to :friend, :class_name => "Person", :foreign_key => "granter_id"
  belongs_to :pending_friend, :class_name => "Person", :foreign_key => "requester_id"
  belongs_to :awaiting_friend, :class_name => "Person", :foreign_key => "granter_id"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :update, :edit, :destroy]
  before_action :authenticate_person!

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_person.friendships.build(:granter_id => params[:granter_id], :accepted => params[:accepted])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to people_url, notice: 'A friend request has been sent to ' + Person.find(params[:granter_id]).name }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update

    respond_to do |format|
      if @friendship.update(params.permit(:id, :accepted))
        # now build a friendship in the opposite direction
        @other_friendship = current_person.friendships.build(:granter_id => @friendship.requester_id, :accepted => true)
        @other_friendship.save

        format.html { redirect_to people_url, notice: 'You and ' + Person.find(@friendship.requester_id).name + ' are now friends!' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    if @friendship.accepted
      @other_friendship = Friendship.find_by :requester_id => @friendship.granter_id, :granter_id => @friendship.requester_id
      @other_friendship.destroy
      notice = 'You and ' + Person.find(@friendship.granter_id).name + ' are no longer friends!'
    else
      notice = 'You have cancelled your friend request to ' + Person.find(@friendship.granter_id).name
    end
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: notice }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:requester_id, :granter_id, :accepted)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requester_id %><br>
    <%= f.text_field :requester_id %>
  </div>
  <div class="field">
    <%= f.label :granter_id %><br>
    <%= f.text_field :granter_id %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br>
    <%= f.check_box :accepted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Friendships</h1>

<table>
  <thead>
    <tr>
      <th>Requester</th>
      <th>Granter</th>
      <th>Accepted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.requester_id %></td>
        <td><%= friendship.granter_id %></td>
        <td><%= friendship.accepted %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requester:</strong>
  <%= @friendship.requester_id %>
</p>

<p>
  <strong>Granter:</strong>
  <%= @friendship.granter_id %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @friendship.accepted %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>