config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :people, controllers: {registrations: "registrations"}
  resources :people do
    resources :wall_posts
  end
  resources :friendships
  resources :groups do
    member do
      post 'people', :to => "groups#add_person", :as => :add_person_to
      delete 'people', :to => "groups#remove_person", :as => :remove_person_from
    end
  end

  resources :wall_posts

  root 'welcome#index'

end

app/models/wall_post.rb
class WallPost < ActiveRecord::Base
  belongs_to :person
  belongs_to :author, :class_name => "Person", :foreign_key => "author_id"
end

app/controllers/wall_posts_controller.rb
class WallPostsController < ApplicationController
  before_action :set_wall_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_person!

  # GET /wall_posts
  # GET /wall_posts.json
  def index
    @wall_posts = WallPost.all
  end

  # GET /wall_posts/1
  # GET /wall_posts/1.json
  def show
  end

  # GET /wall_posts/new
  def new
    @wall_post = WallPost.new
    @person = Person.find(params[:person_id])
  end

  # GET /wall_posts/1/edit
  def edit
  end

  # POST /wall_posts
  # POST /wall_posts.json
  def create
    @person = Person.find(params[:person_id])
    @wall_post = @person.wall_posts.build(wall_post_params)
    @wall_post.date = DateTime.now;
    @wall_post.author = current_person

    respond_to do |format|
      if @wall_post.save
        format.html { redirect_to @person, notice: 'Your post has been added to the wall' }
        format.json { render :show, status: :created, location: @wall_post }
      else
        format.html { render :new }
        format.json { render json: @wall_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wall_posts/1
  # PATCH/PUT /wall_posts/1.json
  def update
    respond_to do |format|
      if @wall_post.update(wall_post_params)
        format.html { redirect_to @wall_post, notice: 'Wall post was successfully updated.' }
        format.json { render :show, status: :ok, location: @wall_post }
      else
        format.html { render :edit }
        format.json { render json: @wall_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wall_posts/1
  # DELETE /wall_posts/1.json
  def destroy
    @wall_post.destroy
    respond_to do |format|
      format.html { redirect_to wall_posts_url, notice: 'Wall post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall_post
      @wall_post = WallPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_post_params
      params.require(:wall_post).permit(:text, :date, :person_id)
    end
end

app/helpers/wall_posts_helper.rb
module WallPostsHelper
end

app/views/wall_posts/_form.html.erb
<%= form_for(@wall_post) do |f| %>
    <% if @wall_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wall_post.errors.count, "error") %> prohibited this wall_post from being saved:</h2>

      <ul>
      <% @wall_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.text_area :text, class: "form-control" %>
  </div>
  <div class="actions">
    <%= hidden_field_tag :person_id, @person.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/wall_posts/_show.html.erb
<p>
  <%= wall_post.text %>
</p>
<small>by <%= link_to wall_post.author.name, person_path(wall_post.author)  %> at <%= DateTime.strptime(wall_post.date).strftime("%H:%M on %m/%d/%Y") %></small>

app/views/wall_posts/edit.html.erb
<h1>Editing Wall Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @wall_post %> |
<%= link_to 'Back', wall_posts_path %>

app/views/wall_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wall Posts</h1>

<%= render 'form' %>
<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wall_posts.each do |wall_post| %>
      <tr>
        <td><%= wall_post.text %></td>
        <td><%= wall_post.date %></td>
        <td><%= link_to 'Show', wall_post %></td>
        <td><%= link_to 'Edit', edit_wall_post_path(wall_post) %></td>
        <td><%= link_to 'Destroy', wall_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <td> <%= link_to 'New Wall post', new_wall_post_path %></td>

        <td><%= button_to "New Wall Post",
                      new_wall_post_path(:id => wall_post.id),
                      :method => :post%></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>


<%= link_to 'New Wall post', new_wall_post_path %>

<div class="form-group">
  <%= f.label 'Update Wall Post' %><br>
  <%= f.text_area :text, class: 'form-control', autofocus: true,
                  placeholder: 'What\'s up?' %>
</div>
<%= f.submit :wall_post, class: 'btn btn-primary'%>

app/views/wall_posts/new.html.erb
<h1>New Wall Post</h1>

<%= render 'form' %>